### ISSUE TITLE
Asset dependency should include yii\web\JqueryAsset

### ISSUE THREAD

**Issue by nick-denry** [fedemotta/yii2-bootstrap-list-filter#2]
Hi! 

BootstrapListFilterAsset.php should include yii\web\YiiAsset or yii\web\JqueryAsset dependency because bootstrap-list-filter.src.js is placed before jQuery.js and cause error "jQuery is not defined" and "jQuery(...).btsListFilter is not a function"

**Comment by fedemotta** [comment]
Hi,
Thanks for your comment. Send me a pull request with the change and I will
merge it.

Cheers

**Comment by nick-denry** [comment]
> Send me a pull request with the change and I will merge it.

Here it is

**Comment by fedemotta** [comment]
Thank you!
